name: Publish
on:
  push:
    branches:
      - main

jobs:
  test-deno:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Run tests
        run: deno task test:deno

  test-node:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm i

      - name: Run tests
        run: npm run test:node

  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    needs: [test-deno, test-node]

    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: Publish package to JSR
        run: npx jsr publish
